dev: NoBody

name: Movie Stream

title: Movie Stream – Nonton pilem geratis

description: Kumpulan Streaming Film Bioskop Terbaru, GRATIS...

avatar: https://cybertecz.in/wp-content/uploads/2019/10/free-movie-streaming-sites.jpg

disqus:

google_analytics: G-KC6YWEG820

url: https://lalajo.moviestream.workers.dev

baseurl: ""

appID-one: 471818d4-b9e8-487d-9041-15cef91e6b84

permalink: /:title

collections:
  tags:
    output: true
    permalink: tags/:path/

version: v4.2.2

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap 
  - jekyll-feed 
  - jekyll-seo 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
