title: Putri's Blog
dev: Putri Dinar

description: My first Jekyll Blog, enjoy...

avatar: https://avatars.githubusercontent.com/u/79742186?v=4

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: putridinar/putridinar.github.io
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: jekyllrb
  stackoverflow:
  youtube: 

disqus: blogsputri

google_analytics:

url: https://putridinar.github.io

baseurl: ""
#

# auth

SITE_KEY: 6LdxkuQqAAAAACMENv8n1QaingZpI997tFWuMKj4
API_KEY: AIzaSyDfZEKaggvi2SN4Jeyhc3XCeb4A1DJVmQE
AUTH_DOMAIN: vems-olshop.firebaseapp.com
DATABASE_URL: https://vems-olshop-default-rtdb.asia-southeast1.firebasedatabase.app
PROJECT_ID: vems-olshop
STORAGE_BUCKET: vems-olshop.firebasestorage.app
SENDER_ID: 281544003271
APP_ID: 1:281544003271:web:1e1d6c0e66f0e4583638e2
MEASUREMENT_ID: G-RGVXFFWN72

paginate: 8
paginate_path: "/page:num/"

markdown: kramdown
highlighter: pygments
permalink: /blog/:title

# The release of Jekyll Now that you're using
version: v4.4.1

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-dotenv

include: ["posts.json"]

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
